name: AWS oidc deployment

on:
  push:
    branches:
      - master

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    

jobs:
  Deploycheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::871194705745:role/oidc_tester
        role-session-name: oidctester
        aws-region: eu-west-1

    - name: GHA deployment using oidc
      run: echo " The oidc is successful"