name: AWS oidc deployment
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::871194705745:role/oidc_tester
        role-session-name: oidctester
        aws-region: eu-west-1

    - name: Deploy
      run: echo " The oidc is successful"