
name: Python application Manual Workflow

on:
  workflow_dispatch:
    branches: [ "master" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Manual trigger
      run: |
         echo " we have manually trigger github actions"

